Repository pyPadaiyal/.github, pull requests merged in 2021-12, with the labels that each got.

#4 Added templates for issues, PR and README along with default LICENSE.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_or_enhancement_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 Added README.md and LICENSE
  LICENSE
  README.md
Labels: documentation

#12 Renamed python build workflow files
  workflow-templates/python_build_clean_test_verify.json
  workflow-templates/python_build_clean_test_verify.png
  workflow-templates/python_build_clean_test_verify.yml
Labels: bug, continuous integration

#14 Renamed python_build_clean_test_verify.json and changed icon image to svg format
  workflow-templates/python_build_clean_test_verify.png
  workflow-templates/python_build_clean_test_verify.properties.json
  workflow-templates/python_build_clean_test_verify.svg
Labels: bug, continuous integration

#16 Separate python build workflow into linting and unit testing workflows
  workflow-templates/python_build.svg
  workflow-templates/python_build_clean_test_verify.properties.json
  workflow-templates/python_linting.properties.json
  workflow-templates/python_linting.yml
  workflow-templates/python_tests.properties.json
  workflow-templates/python_tests.yml
Labels: enhancement, continuous integration
